### ISSUE TITLE
create project crash

### ISSUE THREAD

**Issue by Drapegnik** [lybros/sfm#10]
```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]
```

**Comment by Drapegnik** [comment]
<img width="923" alt="2017-03-01 13 19 43" src="https://cloud.githubusercontent.com/assets/11758660/23464714/10e1c6cc-fea7-11e6-9ee3-eef6477f2fc7.png">

**Comment by UladBohdan** [comment]
Does that crash here every time? Or the crashes are conditional? It is related with where ```Storage::UpdateImagesPath``` called from?

**Comment by Drapegnik** [comment]
It's random, not every time, I can't understand what was wrong.

**Comment by UladBohdan** [comment]
Probably it depends on where is ```images_path``` is assigned.
btw try to change method's signature to ```Storage::UpdateImagesPath(QString&)```

**Comment by UladBohdan** [comment]
Another thing to try is to replace line 19 with
```images_path_ = QString(images_path)``` (creating new object, not sure what operator= does)

**Comment by Drapegnik** [comment]
no one didn't work 😭

**Comment by UladBohdan** [comment]
I haven't met the issue lately.

**Comment by Drapegnik** [comment]
can't reproduce
