### ISSUE TITLE
ui:menu

### ISSUE THREAD

**Issue by Drapegnik** [lybros/sfm#11]
on `Mac OS` after starting app menu with project->new/open don't clickable

**Comment by Drapegnik** [comment]
also some problems with toolbar markup on `Mac OS`
<img width="1090" alt="2017-04-01 23 52 34" src="https://cloud.githubusercontent.com/assets/11758660/24582346/828027b8-1736-11e7-98ab-64bbdbe15c54.png">

**Comment by UladBohdan** [comment]
stupid macOS

**Comment by Drapegnik** [comment]
find related:
https://github.com/robotology/yarp/issues/457

but, don't understand how to fix
