### ISSUE TITLE
code style

### ISSUE THREAD

**Issue by Drapegnik** [lybros/sfm#28]
@UladBohdan, i think we should find some code style, to follow it.
* please use [`cpplint`](https://github.com/cpplint/cpplint) for fixing errors together
* also check if [`cpplint_mac_os.sh`](https://github.com/lybros/sfm/blob/lint/cpplint_mac_os.sh) from [lint-branch](https://github.com/lybros/sfm/tree/lint) work for Linux
* and we can improve lint settings for us, and fix script

Now we have:
```
Category 'build/header_guard' errors found: 2
Category 'build/include_order' errors found: 17
Category 'build/include_subdir' errors found: 20
Category 'build/include_what_you_use' errors found: 7
Category 'legal/copyright' errors found: 1
Category 'readability/alt_tokens' errors found: 1
Category 'readability/casting' errors found: 3
Category 'readability/inheritance' errors found: 2
Category 'runtime/explicit' errors found: 3
Category 'runtime/indentation_namespace' errors found: 2
Category 'runtime/references' errors found: 4
Category 'whitespace/blank_line' errors found: 4
Category 'whitespace/comments' errors found: 1
Category 'whitespace/indent' errors found: 4
Category 'whitespace/line_length' errors found: 2
Category 'whitespace/parens' errors found: 8
Total errors found: 81
```

**Comment by UladBohdan** [comment]
the script works well for linux
as for now, it returns the same bunch of errors.

* the script should be renamed. simple `cpplint.sh` is fine
* what about the line length? Google recommend us to have 80 symbols maximum: https://google.github.io/styleguide/cppguide.html#Line_Length
why would we follow our own rules?

and why discussing that here and not in PR ?

**Comment by Drapegnik** [comment]
* i think we can ignore some rules with script options
* length, name and some other params was fixed
* in PR we can discuss fixes, and checks that code works
* i start fix errors in `src/` and `ui/` for you)

**Comment by UladBohdan** [comment]
have you looked through all script options and sure we don't need to specify anything else?

**Comment by Drapegnik** [comment]
> and we can improve lint settings for us, and fix script

no, we should do this during fix this issue
